server:
  port: 8001 #端口号

spring:
  application:
    name: zero-gateway  # 模块名称
  cloud:
    # 配置中心部分
#    config:
#      name: ${spring.application.name} #  配置文件前缀
#      profile: dev  # 当前版本，同时也是配置文件后缀
#      discovery:
#        enabled: true # 启动发现
#        service-id: SPRINGCLOUD-CONFIG # 配置中心的服务id
    # 网关部分
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由


  # 引入外部yml文件
  profiles:
    include: url,routes
  # 重复的bean进行覆盖
  main:
    allow-bean-definition-overriding: true

# 这部分是Actuator监控设置暴露端点的，以下设置为web服务相关的端点
management:
  endpoint:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:${eureka.instance.port}/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    port: 7001
    instance-id: ${eureka.instance.hostname}:${server.port}
    prefer-ip-address: true
    hostname: ${spring.application.name}

cors:
  origin-url:
    http://localhost:8080,
    http://localhost:8081,
  method:
    GET,
    POST,
    PUT,
    DELETE

# 设置Feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  # 开启时加载
  eager-load:
    enabled: true
    clients: zero-auth
  # 指的是建立连接后服务器读取到可用资源所用的时间，就是服务执行的时间
  ReadTimeout: 5000
  # 指的是建立连接所用的时间，适用于网络状况正常情况下，两端连接所有的时间
  ConnectTimeout: 5000


